services:
  db:
    image: postgres:15
    container_name: medkids_postgres
    environment:
      POSTGRES_USER: medkids
      POSTGRES_PASSWORD: medkids
      POSTGRES_DB: medkids
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
